#!/usr/bin/env python3
"""Save SNTRI station list extracted from browser DOM."""
import json

# Station list extracted from SNTRI homepage dropdowns
# Both "from" and "to" dropdowns contain the same 297 stations
stations = ["A.BEN AHMED", "AIEN ZAKKAR", "AIN DISSA", "AIN DRAHAM", "AIN GUELLAL", "AIN JEMMALA", "AIN SOBH", "AIN SOLTANE", "AIN TONGUA", "AJIM", "AKARIT", "ALEXANDRE", "AMAIEM", "AOUANA", "AOUINET", "B. BOUREGBA", "B. CASERNE", "B. ELAMRI", "B. GUARDEN", "B. HAMOUDA", "B. SAHEL", "B.EL.HAFFEY", "B.EL.IFFA", "B.M'CHERGUA", "B.MESSAOUDI", "BABBOUCHE", "BANNANE", "BEJA", "BEN ABROUG", "BEN AOUN", "BEN SAID", "BENI KHDACHE", "BIR ALI", "BIR CHAOUCH", "BIR JEDID", "BIR LAHMER", "BIR LAOUINI", "BIR TRENTE", "BIZERTE", "BORJ BRAHIM", "BORJ MOUROU", "BORJ TORKI", "BOU SAID", "BOUARADA", "BOUARGOUB", "BOUFICHA", "BOUHAJLA", "BOUKHRIS", "BOUREBIA", "BOUROUIG", "BOUSALEM", "BOUTERFES", "C. SABOUNE", "CHAFFAR", "CHAOUAT", "CHARARDA", "CHARCHARA", "CHASTEL", "D.B.JOUDER", "DEGUECHE", "DEHMANI", "DHIBA", "DJEBBA", "DOUZ", "DRARDA", "E.S.MAKLOUF", "EL AFSA", "EL AJABNA", "EL ALAA", "EL AMRA", "EL BATTEN", "EL FAHS", "EL FAIEDH", "EL GARJOUMA", "EL GOUSSA", "EL GUETTAR", "EL GUIB", "EL HAJEB", "EL HAMMA", "EL HAMMALA", "EL HANCHA", "EL HOUAREB", "EL JEM", "EL KARMA", "EL KHADRA", "EL MAAOUNA", "EL MAY", "EL MDOU", "EL METBASSTA", "ELALIA", "ELFAOUAR", "ELLESSE", "EMB. CHAAL", "EMB. JELMA", "EMB.DEHMANI", "EMB.HAFFOUZ", "EMB.SAKIET", "EMB.SBEITLA", "EMB.SEMENJA", "EMT. KM44", "ENFIDHA", "ENNAIMA", "ENT.ZARZIS", "ESSABRIA", "ESSAFAYA", "ET.TEJEROUIN", "ETTAHOUNA", "F. JEDID", "F. LOUSSIF", "FERIANA", "FERNANA", "FOUCHANA", "FOUSSANA", "FRIQUET", "FURNA", "GAAFOUR", "GABES", "GAFSA", "GARGOUR", "GHOMRASSEN", "GHOMRASSI", "GOUBELLAT", "GROMBALIA", "GUEDIMA", "H. ENNOFS", "H.BOURGUIBA", "HAFFOUZ", "HAMMAM-LIF", "HAZOUA", "HECHICHINA", "HFAIEDH", "HOUMT SOUK", "J. OUEST", "JAFNA", "JALTA", "JEBENIANA", "JEDARA", "JEDEIDA", "JEDLIANE", "JELIDA", "JELMA", "JEMNA", "JENDOUBA", "JERADOU", "JERBA", "JERISSA", "JORF", "K. SENAN", "KABBARA", "KAIROUAN", "KASSERINE", "KEBILI", "KETTANA", "KHANGUET", "KHARROUBA", "KHARROUBET", "KIRCHAW", "KIT.EL.OUED", "KM102", "KM44", "KM74", "KM80", "KM87", "KONDAR", "KRIZ", "KSAR HELAL", "KSAR JEDID", "KSAR NEMSA", "KSOUR ESSAF", "KT.KHESBA", "LA CHEBBA", "LAAYOUNE", "LAKHOUET", "LAKSAB", "LAROUSSA", "LASSOUDA", "LE KEF", "LE KRIB", "LE KSOUR", "LE PALAIS", "LES CHENES", "LIMAGUEZ", "LORBOS", "M'HAMEDIA", "M'SAKEN", "M. MHIRI", "M.BEL ABBES", "M.BOURGUIBA", "MAAROUF", "MAHARES", "MAISONNETTE", "MAKTHAR", "MARETH", "MATEUR", "MATMATA", "MEDENINE", "MEJEZ", "MELLOULECHE", "MENZEL", "METLAOUI", "METOUIA", "MIDOUNE", "MOKNINE", "MORNAGUIA", "MUNCHAR", "N.MATMATA", "NADHOUR", "NADI", "NEBEUR", "NEFTA", "NEFZA", "NEMEMCHA", "O. JEBBAS", "O. LAKSAB", "O.MELLEGUE", "O.TESSA", "O.ZERGUA", "OUECHTATA", "OUED EL GHARE", "OUED KHEDIM", "OUED MELLAH", "OUED RMAL", "OUED SERRAT", "OUEDREF", "OUESLATIA", "OULED DABEB", "OUM.LARAIES", "OUM.LEBOUAB", "PT.MELLEGUE", "RAS JEDIR", "REBIBA", "REDEYEF", "REG.MAATOUG", "REGGUEDA", "REMADA", "RHIMA", "ROBAA", "ROKOB", "ROUHIA", "S. AOUIDET", "S. MANSOUR", "S.BOU ALI", "SAKIET", "SALINES", "SBEITLA", "SBIBA", "SBIKHA", "SEJNANE", "SERS", "SFAX", "SIDI AHMED", "SIDI ALI", "SIDI AMARA", "SIDI AMEUR", "SIDI AMOR", "SIDI AOUDET", "SIDI AYED", "SIDI BOUZID", "SIDI HAMADA", "SIDI HENI", "SIDI KHAIER", "SIDI MTIR", "SIDI NEJI", "SIDI OTHMAN", "SIDI SAID", "SIDI SMAIL", "SILIANA", "SKHIRA", "SLOUGIA", "SMAR", "SOUAR", "SOUK LAHAD", "SOUSSE", "STAFTIMI", "TABARKA", "TAMEGHZA", "TAMEZRAT", "TAMRA", "TATAOUINE", "TEBOURSOUK", "TEDINA", "TEJER.GARE", "TEJEROUINE", "TESTOUR", "THALA", "THIBAR", "TOUIREF", "TOZEUR", "TRIPOLI", "TUNIS NORD", "TUNIS SUD", "VIEUX SERS", "YEBSA", "ZAAFRANA", "ZARZIS"]

# Deduplicate while preserving order
seen = set()
unique = []
for s in stations:
    if s not in seen:
        seen.add(s)
        unique.append(s)

data = {
    "metadata": {
        "source": "SNTRI (sntri.com.tn) homepage station dropdowns",
        "extracted_date": "2026-09-19",
        "total_stations": len(unique),
        "note": "Both from/to dropdowns contain the same 297 stations. SNTRI is a Meteor SPA — data extracted via headless browser DOM.",
    },
    "stations": unique,
}

with open("scripts/sntri_stations.json", "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"Saved {len(unique)} unique SNTRI stations -> scripts/sntri_stations.json")
